language: node_js
node_js: 
  - v12.13.1
services: 
  - mongodb
  - xvfb
  - docker

env: 
  - COMPOSE_VERSION: 1.20.1

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install : 
  - npm install

script : 
  - docker-compose -f docker-compose.test.yml up --build