FROM node:10.12.0-alpine

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait

RUN chmod +x /wait

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

ARG port=80

EXPOSE 80

COPY . ./

CMD /wait && npm run start
