version: '3'
services:
  backend:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.production 
      args:
        port: 80
    restart: always
    ports:
      - "80:80"
    environment:
      WAIT_HOSTS: database:27017
  database:
    image: mongo:4.0
    volumes:
      - "./data/db:/data/db"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=/var/log/mongodb/mongodb.log"